# Generated by Django 4.2.1 on 2023-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('time_date', models.DateTimeField()),
            ],
        ),
    ]
