# Generated by Django 4.2.1 on 2023-06-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mboga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mboga', models.CharField(max_length=32)),
                ('email_address', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=32)),
                ('location_mboga', models.CharField(max_length=32)),
                ('password_mboga', models.CharField(max_length=32)),
            ],
        ),
    ]
