# Generated by Django 4.2.1 on 2023-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Id', models.CharField(max_length=32)),
                ('date_time', models.DateTimeField()),
                ('order_status', models.CharField(max_length=32)),
                ('number_orders', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
